# Generated by Django 3.1 on 2020-08-27 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('name', models.TextField(max_length=200)),
                ('site', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('street', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=200)),
                ('state', models.TextField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
